spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: user-client
          issuer-uri: http://172.30.0.2:8080/realms/stepup
          jwk-set-uri: http://172.30.0.2:8080/realms/stepup/protocol/openid-connect/certs
