spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/stepup
          jwk-set-uri: http://keycloak:8080/realms/stepup/protocol/openid-connect/certs
